# Generated by Django 3.2.3 on 2021-05-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('vehicles', models.CharField(max_length=20)),
                ('movies', models.CharField(max_length=20)),
                ('technology', models.CharField(max_length=20)),
                ('buildings', models.CharField(max_length=20)),
                ('arts', models.CharField(max_length=20)),
                ('science', models.CharField(max_length=20)),
                ('sports', models.CharField(max_length=20)),
                ('bussiness', models.CharField(max_length=20)),
                ('animals', models.CharField(max_length=20)),
                ('birds', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
            ],
        ),
    ]
