# Generated by Django 3.2.3 on 2021-05-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alltags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllTags',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
    ]
